#!/bin/bash

SELFDIR=$(dirname $(readlink -se "${BASH_SOURCE[0]}"))
source $SELFDIR/pk3-utils-source.sh

readme=https://raw.github.com/MarioSMB/esk-modpack/master/README.md
files=$(wget -q -O - $readme | grep -oE "http[^ ]+\.pk3" | grep -vE "quickmenu|hats|vehicles")

for f in $files
do
	file_name=$(basename $f)
	echo -e "\e[32m$file_name\e[0m"
	for d in ${ALL_PK3_DIRS[@]}
	do
		if [ ! -f $d/$file_name ]
		then
			wget -O $d/$file_name $f
		else
			echo -e "\t $d/$file_name already here"
		fi
	done
done

