#!/bin/bash

SELFDIR=$(dirname $(readlink -se "${BASH_SOURCE[0]}"))
source $SELFDIR/source-pk3-utils.sh


SEARCH_FILES=""

function show_help()
{
	echo -e "\e[1mNAME\e[0m"
	echo -e "\t$0 - Search pk3s containing files matching the pattern"
	echo
	echo -e "\e[1mSYNOPSIS\e[0m"
	echo -e "\t\e[1m$0\e[0m [\e[4moptions\e[0m...] \e[4mterm\e[0m..."
	echo -e "\t\e[1m$0\e[0m \e[1mhelp\e[0m|\e[1m-h\e[0m|\e[1m--help\e[0m"
	echo
}


function list_pk3()
{
	if [ -z "$SEARCH_FILES" ]
	then
		ls $XONOTIC_DATA_DIR/*.pk3 
	else
		echo $SEARCH_FILES
	fi
}

function match_pk3()
{
	if pk3_files $1 | grep -q $2
	then
		echo $1
	fi
}


for arg in $@
do
	case $arg in
		
		help|--help|-h)
			show_help
			;;
		*.pk3)
			SEARCH_FILES="$SEARCH_FILES $arg"
			;;
		*)
			for pk3 in $(list_pk3)
			do
				match_pk3 $pk3 $arg
			done
		
	esac
done