#!/bin/bash

GEN_MAPINFO_GAMETYPES="dm tdm ft kh"

SELFDIR=$(dirname $(readlink -se "${BASH_SOURCE[0]}"))
source $SELFDIR/source-pk3-utils.sh

GEN_MAPINFO_OUT_DIR=$XONOTIC_DATA_DIR/maps


function mapinfo()
{
	if [ ! -d $GEN_MAPINFO_OUT_DIR ]
	then
		mkdir -p $GEN_MAPINFO_OUT_DIR
	fi
	
	echo Checking Mapinfo for $1...
	
	if ! pk3_is_map $1
	then
		echo "    not a map pk3"
		return 0
	fi
	
	maps=$(pk3_maps $1)
	declare -i issues
	let issues=0
	
	for map in $maps
	do
		map_name=`basename $map .bsp`
		mapinfo_file=$GEN_MAPINFO_OUT_DIR/$map_name.mapinfo
		echo "    Generating mapinfo for $map"
		
		if [ ! -f $mapinfo_file ]
		then
			if pk3_contains $1 maps/$map_name.mapinfo
			then
				unzip -p $1 maps/$map_name.mapinfo >$mapinfo_file
			else
				create_mapinfo $GEN_MAPINFO_OUT_DIR $map_name 7
			fi
		fi
		
		for gametype in $GEN_MAPINFO_GAMETYPES
		do
			if ! grep -qE "^(game)type\s+$gametype" $mapinfo_file
			then
				echo "        Adding $gametype"
				echo "gametype $gametype" >>$mapinfo_file
			fi
		done
	done
}

for arg in $@
do
	
	case $arg in
		*.pk3)
			mapinfo $arg
			;;
		*)
			echo Skipping unknown option $arg
			;;
	esac
done
