#!/bin/bash
# An example plugin
# Note: toggle the execution permission to enable or disable this plugin.

if [ "$1" = "help" ]
then
	echo An example plugin
	exit 0
elif [ "$1" = "synopsis" ]
then
	echo -n "\e[4mparams\e[0m"
	exit 0
fi


echo Test plugin "${@}"